### PR TITLE
Cursor Management

### PR DESCRIPTION
**Pull request by RobWood8426**
Fixing issue #78

@tonsky Let me know if this is suitable or if you would like to approach the issue another way.

Allow for correct state when you transition from within one text input to another.

### CODE REVIEW

**Comment by tonsky** [comment]
No, this will set cursor on every mouse move while inside. I’m not sure what the right solution here is, maybe something should track who set cursor and then e.g. text-field2 unsetting cursor would not undo text-field1 setting it

**Comment by RobWood8426** [comment]
This is a fair point. 
Let me rework this to a more correct solution.

The options I can see would be:

1. Like you say maintain some extra state that knows who last set the cursor. (I feel like this might have some nuance) 
2. On mouse move get the current cursor to inform if you need to change the cursor (This is probably the least complex way to achieve correct behaviour. We are still checking every frame, but we are already doing the rect boundary maths each frame, so I don't think this creates any performance issues)
3. Create some amount of order of events? Such that your leave events fire before your entry events (Basically what our 1px gap was achieving)

Let me know your preference and I will try to work together a solution.

**Comment by tonsky** [comment]
I was thinking about something like this:

```
(def *cursor
  (atom {}))

(defn request-cursor! [key cursor]
  (swap! *cursor assoc key cursor))

(defn unrequest-cursor! [key]
  (swap! *cursor dissoc key))

(add-watch *cursor ::set
  (fn [_ _ old new]
    (let [before (or (first (vals old)) :arrow)
          after  (or (first (vals new)) :arrow)]
      (when (not= before after)
        (window/set-cursor window after)))))
```

So if two components request cursor, it gets set to any of them. If none requests, it gets reset back to arrow. Beauty of it is, it doesn’t matter in which order components request/unrequest cursor for them.

**Comment by RobWood8426** [comment]
Upon more discussion we decided this would best be solved once lifecycles are added into HumbleUI 
So will close this PR and pick it up once those are available.

**Pull request closed without merging**
